# Generated by Django 5.0.6 on 2024-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_img', models.ImageField(upload_to='my_informatin')),
                ('p_det', models.TextField()),
            ],
        ),
    ]
